#!/usr/bin/env tsx
/* ─── Inject Glossary Box ────────────────────────────────────────────────────
   For each .md chapter in <srcDir>:
     1. Read the chapter text + the central glossary.json
     2. For each glossary entry whose term appears at least once in the
        chapter (whole-word match, case-sensitive for acronyms,
        case-insensitive otherwise), include it in a per-chapter
        "Concepts at a glance" box.
     3. Insert the box right after the chapter's first H2 heading section
        (typically "## Why this matters at Qualcomm" or "## The 90-second
        story"). Idempotent — replaces an existing auto-generated box if
        present (delimited by HTML comments).

   Usage:
     npx tsx scripts/atheneum/inject-glossary.ts <srcDir> [--dry-run] [--force]
     [--worst=N]   # only inject into the N worst chapters per jargon-audit

   Skips chapters already containing a HAND-CURATED glossary (matched
   "## Concepts at a glance" without the auto-generated comment marker)
   unless --force is passed.
───────────────────────────────────────────────────────────────────────────── */

import { promises as fs } from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..')
const GLOSSARY_PATH = path.join(ROOT, 'content/qualcomm-compiler/glossary.json')
const AUDIT_PATH = path.join(ROOT, 'build/jargon-audit.json')

const AUTOGEN_OPEN = '<!-- ATHENEUM:auto-glossary:start -->'
const AUTOGEN_CLOSE = '<!-- ATHENEUM:auto-glossary:end -->'

interface GlossaryEntry {
  category: string
  gloss: string
  deepDive: string
}
interface Glossary {
  _schema: number
  bookId: string
  entries: Record<string, GlossaryEntry>
}

interface ChapterAudit {
  filePath: string
  filename: string
  section: string
  unintroducedTerms: Array<{ term: string; mentions: number }>
  hasGlossaryBox: boolean
  infoDumpScore: number
}

const CATEGORY_GROUPS: Array<{ category: string; heading: string }> = [
  { category: 'frontend',    heading: 'Frontend / Clang' },
  { category: 'middle-end',  heading: 'Middle-end / IR optimizer' },
  { category: 'backend',     heading: 'Backend / codegen' },
  { category: 'llvm-core',   heading: 'LLVM core' },
  { category: 'cpp',         heading: 'C++' },
  { category: 'linker',      heading: 'Linker / runtime' },
  { category: 'os',          heading: 'OS' },
  { category: 'arch',        heading: 'Computer architecture' },
  { category: 'hexagon',     heading: 'Hexagon' },
  { category: 'math',        heading: 'Math / numerics' },
]

function buildTermRegex(term: string): RegExp {
  // Whole-word boundary on both sides; escape regex specials.
  const esc = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  // Acronym (≥2 uppercase) → case-sensitive; lowercase term → case-insensitive
  const flags = /^[A-Z]{2,}\d?$/.test(term) ? 'g' : 'gi'
  return new RegExp(`\\b${esc}\\b`, flags)
}

function termAppearsIn(term: string, text: string): boolean {
  return buildTermRegex(term).test(text)
}

function generateBox(glossary: Glossary, chapterText: string): string | null {
  const matched: Record<string, [string, GlossaryEntry][]> = {}
  for (const [term, entry] of Object.entries(glossary.entries)) {
    if (!termAppearsIn(term, chapterText)) continue
    const cat = entry.category
    if (!matched[cat]) matched[cat] = []
    matched[cat].push([term, entry])
  }
  const totalMatched = Object.values(matched).reduce((a, c) => a + c.length, 0)
  if (totalMatched < 4) return null  // fewer than 4 terms — skip the box

  const lines: string[] = []
  lines.push(AUTOGEN_OPEN)
  lines.push('## Concepts at a glance')
  lines.push('')
  lines.push('> Auto-generated by the Atheneum compiler. If a term in the rest of this chapter feels dropped-in, this is the cheat sheet. Each entry has the one-line *what it does* answer; the `→ §` link points to the chapter that covers it in full.')
  lines.push('')
  for (const group of CATEGORY_GROUPS) {
    const rows = matched[group.category]
    if (!rows || rows.length === 0) continue
    lines.push(`**${group.heading}**`)
    lines.push('')
    lines.push('| Term | One-line gloss | Deep dive |')
    lines.push('|---|---|---|')
    rows.sort((a, b) => a[0].localeCompare(b[0]))
    for (const [term, entry] of rows) {
      const gloss = entry.gloss.replace(/\|/g, '\\|')
      const dive = entry.deepDive.replace(/\|/g, '\\|')
      lines.push(`| **${term}** | ${gloss} | ${dive} |`)
    }
    lines.push('')
  }
  lines.push(AUTOGEN_CLOSE)
  return lines.join('\n')
}

/** Insert the box AFTER the first H2 (or at top after H1+blockquote+image
 *  if no H2 exists). Replaces existing autogen marker pair if present. */
function injectBox(chapterText: string, box: string): string {
  // Already has an auto-block? Replace it.
  const autogenRE = new RegExp(`${AUTOGEN_OPEN}[\\s\\S]*?${AUTOGEN_CLOSE}`, 'g')
  if (autogenRE.test(chapterText)) {
    return chapterText.replace(autogenRE, box)
  }

  // Find the first H2 — insert AFTER its section ends (i.e., right before
  // the next H2). If no H2 exists, append to end.
  const lines = chapterText.split('\n')
  let firstH2 = -1
  let secondH2 = -1
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+/.test(lines[i])) {
      if (firstH2 === -1) firstH2 = i
      else { secondH2 = i; break }
    }
  }
  if (firstH2 === -1) {
    // No H2 — append at end.
    return chapterText + '\n\n' + box + '\n'
  }
  const insertAt = secondH2 === -1 ? lines.length : secondH2
  const prefix = lines.slice(0, insertAt).join('\n').replace(/\n+$/, '\n')
  const suffix = lines.slice(insertAt).join('\n')
  return prefix + '\n' + box + '\n\n' + suffix
}

async function main() {
  const argv = process.argv.slice(2)
  const srcDir = argv[0]
  const dryRun = argv.includes('--dry-run')
  const force = argv.includes('--force')
  const worstArg = argv.find(a => a.startsWith('--worst='))
  const worstN = worstArg ? Number(worstArg.split('=')[1]) : null

  if (!srcDir) {
    console.error('usage: inject-glossary.ts <srcDir> [--dry-run] [--force] [--worst=N]')
    process.exit(1)
  }

  const glossary = JSON.parse(await fs.readFile(GLOSSARY_PATH, 'utf-8')) as Glossary
  console.log(`▸ inject-glossary  glossary entries: ${Object.keys(glossary.entries).length}`)
  console.log(`  src: ${srcDir}`)
  if (dryRun) console.log('  [DRY RUN]')
  if (force) console.log('  [FORCE]')

  // Optional: filter by worst-N from the audit
  let chapterFilter: Set<string> | null = null
  if (worstN !== null) {
    const audit = JSON.parse(await fs.readFile(AUDIT_PATH, 'utf-8')) as ChapterAudit[]
    const worst = [...audit]
      .filter(a => !a.hasGlossaryBox)
      .sort((b, a) => a.infoDumpScore - b.infoDumpScore)
      .slice(0, worstN)
    chapterFilter = new Set(worst.map(a => a.filePath))
    console.log(`  scope: top ${worstN} worst chapters (by info-dump score)`)
  }

  const sections = (await fs.readdir(srcDir, { withFileTypes: true }))
    .filter(e => e.isDirectory() && /^\d/.test(e.name))
    .map(e => e.name)
    .sort()

  let injected = 0
  let skippedManual = 0
  let skippedTooFewTerms = 0
  let skippedNotInScope = 0

  for (const sec of sections) {
    const secDir = path.join(srcDir, sec)
    const files = (await fs.readdir(secDir, { withFileTypes: true }))
      .filter(e => e.isFile() && e.name.endsWith('.md'))
      .map(e => e.name)
      .sort()
    for (const f of files) {
      const fp = path.join(secDir, f)
      if (chapterFilter && !chapterFilter.has(fp)) {
        skippedNotInScope += 1
        continue
      }
      const stat = await fs.stat(fp)
      if (stat.size < 500) continue
      const text = await fs.readFile(fp, 'utf-8')

      // Check for hand-curated glossary box (no autogen marker)
      const hasManualBox = /^##\s+Concepts at a glance\b/im.test(text) && !text.includes(AUTOGEN_OPEN)
      if (hasManualBox && !force) {
        skippedManual += 1
        continue
      }

      const box = generateBox(glossary, text)
      if (!box) {
        skippedTooFewTerms += 1
        continue
      }
      const newText = injectBox(text, box)
      const matched = (newText.match(/\| \*\*[^*]+\*\* \|/g) ?? []).length
      console.log(`  ${sec}/${f.padEnd(40)} ${matched} term-rows`)
      if (!dryRun) await fs.writeFile(fp, newText)
      injected += 1
    }
  }

  console.log('')
  console.log(`  injected:       ${injected}`)
  console.log(`  skipped manual: ${skippedManual} (use --force to override)`)
  console.log(`  too few terms:  ${skippedTooFewTerms}`)
  if (chapterFilter) console.log(`  out of scope:   ${skippedNotInScope}`)
}

main().catch(e => { console.error('inject failed:', e); process.exit(1) })
