/* ─── LaTeX Preamble for the Atheneum PDF Backend ───────────────────────────
   Memoir-class book preamble with:
     - lualatex + fontspec for OTF font loading
     - EB Garamond / Inter / JetBrains Mono with graceful fallbacks
     - microtype for kerning + protrusion
     - minted (Pygments) for color syntax highlighting w/ Unicode support
     - tcolorbox for cookbook callout variants (tip/warning/key/example/def/note)
     - lettrine for drop caps on chapter openers
     - fancy chapter pages with epigraph + ornament rule + Title-Case display
     - frontmatter / mainmatter / backmatter discipline
     - running heads: chapter title (left), section (right), folio (outer)
     - hyperref for clickable TOC and cross-refs
     - tikz for inline custom-svg block rendering (delegated to engines)
     - \conceptref{slug} command for [[concept]] refs (rendered as small caps)
     - \code{...} command for inline code (subtle gray box, mono)

   Designed to compile with `lualatex -shell-escape` (minted needs shell-escape).
   Falls back gracefully when EB Garamond / Inter aren't installed — uses
   Cardo / Linux Libertine / Latin Modern. Build never fails on font absence.
───────────────────────────────────────────────────────────────────────────── */

import type { Chapter } from '../../../src/types/book.ts'

export interface PreambleOptions {
  bookTitle: string
  bookSubtitle?: string
  author: string
  /** "book" (full doc), "chapter" (single-chapter standalone), or "mini" (cab-read A5). */
  shape: 'book' | 'chapter' | 'mini'
  /** When set, pin paper size. Default A4 for `book`, A5 for `mini`. */
  paperSize?: 'a4paper' | 'a5paper' | 'letterpaper'
  /** Body text size in pt. Default 11 for book, 10 for mini. */
  fontSize?: number
}

export function preamble(opts: PreambleOptions): string {
  const paper = opts.paperSize ?? (opts.shape === 'mini' ? 'a5paper' : 'a4paper')
  const fontSize = opts.fontSize ?? (opts.shape === 'mini' ? 10 : 11)

  return `% !TEX TS-program = lualatex
% !TEX encoding = UTF-8
% Atheneum book — generated by PdfBackend
\\documentclass[${fontSize}pt,${paper},twoside,openright]{memoir}

% ─── Geometry ─────────────────────────────────────────────────────
\\usepackage[
  ${opts.shape === 'mini' ? 'inner=0.6in, outer=0.5in, top=0.6in, bottom=0.7in' : 'inner=1.1in, outer=0.9in, top=1in, bottom=1.1in, headheight=14pt'}
]{geometry}

% ─── Font loading (lualatex/xelatex via fontspec) ─────────────────
\\usepackage{fontspec}
\\usepackage{microtype}      % kerning + protrusion

% Body: try EB Garamond → Cardo → Linux Libertine → fall back to default
\\IfFontExistsTF{EB Garamond}{
  \\setmainfont[Numbers={OldStyle},Ligatures=TeX]{EB Garamond}
}{\\IfFontExistsTF{Cardo}{
  \\setmainfont[Numbers={OldStyle},Ligatures=TeX]{Cardo}
}{\\IfFontExistsTF{Linux Libertine O}{
  \\setmainfont[Ligatures=TeX]{Linux Libertine O}
}{}}}

% Sans (UI / running heads): Inter → Helvetica Neue → default
\\IfFontExistsTF{Inter}{
  \\setsansfont[Ligatures=TeX,Scale=0.95]{Inter}
}{\\IfFontExistsTF{Helvetica Neue}{
  \\setsansfont[Scale=0.95]{Helvetica Neue}
}{}}

% Mono (code + UI accents): JetBrains Mono → Menlo → default
\\IfFontExistsTF{JetBrains Mono}{
  \\setmonofont[Scale=0.85,Ligatures=TeX]{JetBrains Mono}
}{\\IfFontExistsTF{JetBrainsMonoNerdFont-Regular.ttf}{
  \\setmonofont[Scale=0.85,Path=/Users/r-amogh/Library/Fonts/]{JetBrainsMonoNerdFont-Regular.ttf}[
    BoldFont=JetBrainsMonoNerdFont-Bold.ttf,
    ItalicFont=JetBrainsMonoNerdFont-Italic.ttf,
    BoldItalicFont=JetBrainsMonoNerdFont-BoldItalic.ttf,
  ]
}{\\IfFontExistsTF{Menlo}{
  \\setmonofont[Scale=0.85]{Menlo}
}{}}}

% ─── Core packages ────────────────────────────────────────────────
\\usepackage[english]{babel}
\\usepackage{amsmath}        % \\text inside math, align, etc.
\\usepackage{amssymb}
\\usepackage{newunicodechar}
\\newunicodechar{₹}{\\ifmmode\\text{Rs.\\,}\\else Rs.\\,\\fi}
\\newunicodechar{✓}{\\checkmark}
\\newunicodechar{✗}{\\texttimes}
\\newunicodechar{∅}{\\ensuremath{\\varnothing}}
\\newunicodechar{≥}{\\ensuremath{\\geq}}
\\newunicodechar{≤}{\\ensuremath{\\leq}}
\\newunicodechar{⊤}{\\ensuremath{\\top}}
\\newunicodechar{⊥}{\\ensuremath{\\bot}}
\\newunicodechar{∈}{\\ensuremath{\\in}}
\\newunicodechar{∀}{\\ensuremath{\\forall}}
\\newunicodechar{∃}{\\ensuremath{\\exists}}
\\newunicodechar{→}{\\ensuremath{\\rightarrow}}
\\newunicodechar{←}{\\ensuremath{\\leftarrow}}
\\newunicodechar{↔}{\\ensuremath{\\leftrightarrow}}
\\newunicodechar{≈}{\\ensuremath{\\approx}}
\\newunicodechar{×}{\\ensuremath{\\times}}
\\newunicodechar{·}{\\ensuremath{\\cdot}}
\\newunicodechar{…}{\\ensuremath{\\ldots}}
\\usepackage[hyphens]{url}
\\usepackage[
  hidelinks,
  pdftitle={${escapePdfMeta(opts.bookTitle)}},
  pdfauthor={${escapePdfMeta(opts.author)}}
]{hyperref}
\\usepackage{xcolor}
\\usepackage{graphicx}
\\usepackage{enumitem}
\\usepackage{lettrine}
\\usepackage{epigraph}
\\usepackage{soul}            % \\sout for strikethrough
\\usepackage{ulem}\\normalem  % \\uline (for inline underline) without redefining \\emph
\\usepackage{tcolorbox}
\\tcbuselibrary{breakable,skins}
\\usepackage{minted}
\\usemintedstyle{tango}
\\setminted{
  fontsize=\\small,
  breaklines=true,
  frame=leftline,
  framesep=8pt,
  linenos=false,
  numbersep=8pt,
  bgcolor=athenaeumCodeBg,
}

% ─── Brand colors (mirrors design tokens) ─────────────────────────
\\definecolor{athenaeumInk}{HTML}{1A1614}
\\definecolor{athenaeumBone}{HTML}{F5F1EA}
\\definecolor{athenaeumOxblood}{HTML}{7B2D26}
\\definecolor{athenaeumSeal}{HTML}{2E2A28}
\\definecolor{athenaeumAmber}{HTML}{C28840}
\\definecolor{athenaeumIndigo}{HTML}{2A4D6E}
\\definecolor{athenaeumMoss}{HTML}{4A6B3F}
\\definecolor{athenaeumCodeBg}{HTML}{F8F6F2}
\\definecolor{athenaeumRule}{HTML}{C8BFA9}

% ─── Cookbook callout boxes (tcolorbox styles) ────────────────────
\\newtcolorbox{tipbox}[1][]{
  enhanced, breakable, sharp corners, colback=athenaeumBone, colframe=athenaeumIndigo,
  boxrule=0.4pt, leftrule=2.5pt, left=10pt, right=8pt, top=6pt, bottom=6pt,
  fonttitle=\\sffamily\\bfseries, title={Tip}, #1
}
\\newtcolorbox{warnbox}[1][]{
  enhanced, breakable, sharp corners, colback=athenaeumBone, colframe=athenaeumOxblood,
  boxrule=0.4pt, leftrule=2.5pt, left=10pt, right=8pt, top=6pt, bottom=6pt,
  fonttitle=\\sffamily\\bfseries, title={Trap}, #1
}
\\newtcolorbox{keybox}[1][]{
  enhanced, breakable, sharp corners, colback=athenaeumBone, colframe=athenaeumAmber,
  boxrule=0.4pt, leftrule=2.5pt, left=10pt, right=8pt, top=6pt, bottom=6pt,
  fonttitle=\\sffamily\\bfseries, title={Key concept}, #1
}
\\newtcolorbox{exbox}[1][]{
  enhanced, breakable, sharp corners, colback=athenaeumBone, colframe=athenaeumMoss,
  boxrule=0.4pt, leftrule=2.5pt, left=10pt, right=8pt, top=6pt, bottom=6pt,
  fonttitle=\\sffamily\\bfseries, title={Example}, #1
}
\\newtcolorbox{defbox}[1][]{
  enhanced, breakable, sharp corners, colback=athenaeumBone, colframe=athenaeumSeal,
  boxrule=0.4pt, leftrule=2.5pt, left=10pt, right=8pt, top=6pt, bottom=6pt,
  fonttitle=\\sffamily\\bfseries, title={Definition}, #1
}
\\newtcolorbox{notebox}[1][]{
  enhanced, breakable, sharp corners, colback=athenaeumBone!50, colframe=athenaeumRule,
  boxrule=0.4pt, leftrule=2pt, left=10pt, right=8pt, top=6pt, bottom=6pt, #1
}

% ─── Chapter style: drop cap + epigraph + ornament rule ──────────
\\setlength{\\epigraphwidth}{0.65\\textwidth}
\\renewcommand{\\epigraphsize}{\\itshape\\small}
\\renewcommand{\\epigraphflush}{flushright}

\\chapterstyle{section}
\\setlength{\\beforechapskip}{1.2in}
\\setlength{\\afterchapskip}{0.5in}
\\renewcommand{\\chapterheadstart}{}
\\renewcommand{\\chapnumfont}{\\sffamily\\Huge\\color{athenaeumOxblood}}
\\renewcommand{\\chaptitlefont}{\\sffamily\\bfseries\\Huge\\color{athenaeumInk}}
\\renewcommand{\\printchapternum}{}  % we'll emit chapter numbers in title
\\renewcommand{\\afterchapternum}{}
\\renewcommand{\\printchapternonum}{}

% ─── Running heads (chapter on left, section on right) ───────────
\\makepagestyle{atheneumheads}
\\makeevenhead{atheneumheads}{\\thepage}{}{\\sffamily\\small\\itshape\\leftmark}
\\makeoddhead{atheneumheads}{\\sffamily\\small\\itshape\\rightmark}{}{\\thepage}
\\makeheadrule{atheneumheads}{\\textwidth}{0.4pt}
\\pagestyle{atheneumheads}
\\renewcommand{\\chaptermark}[1]{\\markboth{#1}{}}
\\renewcommand{\\sectionmark}[1]{\\markright{#1}}

% ─── Inline code style (\\code{}) ─────────────────────────────────
\\newcommand{\\code}[1]{\\colorbox{athenaeumCodeBg}{\\texttt{\\small #1}}}

% ─── Concept reference (\\conceptref{slug}) ──────────────────────
% Rendered as small-caps amber. Linked-anchor support comes in a later phase.
\\newcommand{\\conceptref}[1]{\\textsc{\\textcolor{athenaeumAmber}{#1}}}

% ─── Ornament divider for triple-dash blocks ────────────────────
\\newcommand{\\athornament}{\\par\\bigskip\\centerline{\\textcolor{athenaeumRule}{\\rule{0.4\\textwidth}{0.5pt}}\\enspace\\textcolor{athenaeumAmber}{$\\diamond$}\\enspace\\textcolor{athenaeumRule}{\\rule{0.4\\textwidth}{0.5pt}}}\\par\\bigskip}

% ─── List spacing (cookbook §universal: tight) ───────────────────
\\setlist{itemsep=0.2em, topsep=0.4em, parsep=0pt}

% ─── Title metadata ──────────────────────────────────────────────
\\title{${escapePreambleString(opts.bookTitle)}}
${opts.bookSubtitle ? `\\newcommand{\\booksubtitle}{${escapePreambleString(opts.bookSubtitle)}}` : ''}
\\author{${escapePreambleString(opts.author)}}
\\date{}

\\begin{document}
`
}

/** Escape strings that go into preamble metadata (pdftitle, etc.). */
function escapePdfMeta(s: string): string {
  return s.replace(/[\\{}()]/g, ' ').replace(/[—–]/g, '-')
}

/** Escape strings used in TeX preamble text bodies (\\title{}, etc.). */
function escapePreambleString(s: string): string {
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
}

// ─── Front-matter / chapter-page helpers ───────────────────────────

export function frontMatter(opts: { title: string; subtitle?: string; author: string }): string {
  return `\\frontmatter
\\begin{titlingpage}
\\centering
\\vspace*{2in}
{\\sffamily\\Huge\\bfseries\\color{athenaeumInk} ${escapePreambleString(opts.title)}\\par}
${opts.subtitle ? `\\vspace{0.4in}{\\itshape\\large\\color{athenaeumOxblood} ${escapePreambleString(opts.subtitle)}\\par}` : ''}
\\vfill
{\\sffamily\\large\\color{athenaeumSeal} ${escapePreambleString(opts.author)}\\par}
\\vspace{0.5in}
\\end{titlingpage}
\\cleardoublepage
\\tableofcontents*
\\cleardoublepage
\\mainmatter
`
}

export function backMatter(): string {
  return `\\backmatter
\\cleardoublepage
\\thispagestyle{empty}
\\vspace*{\\fill}
\\begin{center}
\\textit{Bound, signed, ready.}\\par
\\vspace{1em}
\\textcolor{athenaeumAmber}{$\\diamond$}\\par
\\end{center}
\\vspace*{\\fill}
\\end{document}
`
}

/** Open a chapter with epigraph + drop cap (caller provides the first
 *  paragraph after this if they want lettrine; we just emit the heading +
 *  optional epigraph here). */
export function chapterOpener(ch: Chapter): string {
  const safeTitle = ch.title
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
  const epigraph = ch.subtitle
    ? `\\epigraph{${ch.subtitle.replace(/\\/g, '\\textbackslash{}').replace(/([&%$#_{}])/g, '\\$1')}}{}`
    : ''
  return `\\chapter{${safeTitle}}\n${epigraph}\n`
}
